# Generated by Django 5.2.1 on 2025-05-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 звёзд'), (2, '2 звёзды'), (3, '3 звёзды'), (4, '4 звёзды'), (5, '5 звёзды')], default=5, verbose_name='Оценка'),
        ),
    ]
